### ISSUE TITLE
Cannot connect to 88015 hub

### ISSUE THREAD

**Issue by soql** [undera/pylgbst#114]
I have no problem to connect to move hub (with 2 builded-in motors) but cannot connect 88015 generic hub (with 2 interfaces). On RPI and laptop linux I have:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pylgbst/comms/cbleak.py", line 50, in <lambda>
    self._connection_thread = threading.Thread(target=lambda: asyncio.run(self._bleak_thread()))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.8/site-packages/pylgbst/comms/cbleak.py", line 69, in _bleak_thread
    await bleak.write(data[0], data[1])
  File "/home/user/.local/lib/python3.8/site-packages/pylgbst/comms/cbleak.py", line 180, in write
    await self._client.write_gatt_char(MOVE_HUB_HW_UUID_CHAR, data)
  File "/home/user/.local/lib/python3.8/site-packages/bleak/backends/bluezdbus/client.py", line 751, in write_gatt_char
    raise BleakError("Not connected")
bleak.exc.BleakError: Not connected

**Comment by soql** [comment]
It`s ok with gatt bluetooth backend both on rpi zero 2 and ubuntu :)
