### ISSUE TITLE
'MoveHub' object has no attribute 'connection'

### ISSUE THREAD

**Issue by TravelTrader** [undera/pylgbst#117]
I'd really like to code the boost in Python but I couldn't even start the basics.

I get this error:
```
ERROR:pygatt.backends.gatttool.gatttool:Unexpected error when scanning: Set scan parameters failed: Operation not permitted

Traceback (most recent call last):
  File "pylgbst_detect_hub.py", line 3, in <module>
    hub = MoveHub()
  File "/home/trader/.local/lib/python3.6/site-packages/pylgbst/hub.py", line 231, in __init__
    connection = get_connection_auto(hub_name=self.DEFAULT_NAME)
  File "/home/trader/.local/lib/python3.6/site-packages/pylgbst/__init__.py", line 75, in get_connection_auto
    raise Exception("Failed to autodetect connection, make sure you have installed prerequisites")
Exception: Failed to autodetect connection, make sure you have installed prerequisites
Exception ignored in: <bound method Hub.__del__ of <pylgbst.hub.MoveHub object at 0x7f5fa0ec46d8>>
Traceback (most recent call last):
  File "/home/trader/.local/lib/python3.6/site-packages/pylgbst/hub.py", line 76, in __del__
    if self.connection and self.connection.is_alive():
AttributeError: 'MoveHub' object has no attribute 'connection'
```
For example when I run:

```
from pylgbst.hub import MoveHub

hub = MoveHub()

for device in hub.peripherals:
    print(device)
```

Could you help me, please?
Running it under Ubuntu 18.04. - thanks!

**Comment by undera** [comment]
Try installing Bleak backend library. It should work better.
In your case of using Gattool, you probably have to run it with `sudo`

**Comment by TravelTrader** [comment]
Awesome!!
I added bleak and it worked. The Boost is detected.

Thank you so much!
